// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
	"math/big"
	"twst/internal/sdk/pkg/models/shared"
)

func (r *OrderDataSourceModel) RefreshFromGetResponse(resp *shared.Order) {
	if resp.Description != nil {
		r.Description = types.StringValue(*resp.Description)
	} else {
		r.Description = types.StringNull()
	}
	r.ID = types.Int64Value(resp.ID)
	r.Image = types.StringValue(resp.Image)
	r.Name = types.StringValue(resp.Name)
	r.Price = types.NumberValue(big.NewFloat(float64(resp.Price)))
	r.Teaser = types.StringValue(resp.Teaser)
}
